function create_room(e, instance)
	math.randomseed(os.time())
	action(e, instance, '"type": "window", "w": 768, "h": 768')
	action(e, instance, '"type": "music", "file": "music.ogg"')
	local player = spawn(e, instance, "player.json", 384, 384, false)
	local corner_tl = spawn(e, instance, "corner.json", 32, 32, false)
	action(e, corner_tl, '"type": "rotation", "angle": 0')
	local corner_tr = spawn(e, instance, "corner.json", 736, 32, false)
	action(e, corner_tr, '"type": "rotation", "angle": 90')
	local corner_br = spawn(e, instance, "corner.json", 736, 736, false)
	action(e, corner_br, '"type": "rotation", "angle": 180')
	local corner_bl = spawn(e, instance, "corner.json", 32, 736, false)
	action(e, corner_bl, '"type": "rotation", "angle": 270')
	local wall_t = spawn(e, instance, "wall_t.json", 384, 32, false)
	local wall_r = spawn(e, instance, "wall_r.json", 736, 384, false)
	local wall_b = spawn(e, instance, "wall_b.json", 384, 736, false)
	local wall_l = spawn(e, instance, "wall_l.json", 32, 384, false)
	action(e, instance, '"type": "timer", "num": 0, "time": 5')
	action(e, instance, '"type": "timer", "num": 1, "time": 5')
end
